apiVersion: v1
kind: Service
metadata:
  name: accountservice
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  selector:
    app: accountsvc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer